[Fri Jan 13 14:38:04.582409 2017] [wsgi:error] [pid 12:tid 140470552831744] [remote 128.211.233.228:58578] mod_wsgi (pid=12): Target WSGI script '/srv/www/app/apache/apache.wsgi' cannot be loaded as Python module.
[Fri Jan 13 14:38:04.582593 2017] [wsgi:error] [pid 12:tid 140470552831744] [remote 128.211.233.228:58578] mod_wsgi (pid=12): Exception occurred processing WSGI script '/srv/www/app/apache/apache.wsgi'.
[Fri Jan 13 14:38:04.582949 2017] [wsgi:error] [pid 12:tid 140470552831744] [remote 128.211.233.228:58578] Traceback (most recent call last):
[Fri Jan 13 14:38:04.583001 2017] [wsgi:error] [pid 12:tid 140470552831744] [remote 128.211.233.228:58578]   File "/srv/www/app/apache/apache.wsgi", line 10, in <module>
[Fri Jan 13 14:38:04.583105 2017] [wsgi:error] [pid 12:tid 140470552831744] [remote 128.211.233.228:58578]     from main import app as application
[Fri Jan 13 14:38:04.583142 2017] [wsgi:error] [pid 12:tid 140470552831744] [remote 128.211.233.228:58578]   File "/srv/www/app/main.py", line 15, in <module>
[Fri Jan 13 14:38:04.583719 2017] [wsgi:error] [pid 12:tid 140470552831744] [remote 128.211.233.228:58578]     imgData = os.listdir(ROOT_DIR + "/static/data/imgData")
[Fri Jan 13 14:38:04.583780 2017] [wsgi:error] [pid 12:tid 140470552831744] [remote 128.211.233.228:58578] OSError: [Errno 2] No such file or directory: '/srv/www/app/static/data/imgData'
[Fri Jan 13 14:38:04.599254 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578] mod_wsgi (pid=12): Target WSGI script '/srv/www/app/apache/apache.wsgi' cannot be loaded as Python module.
[Fri Jan 13 14:38:04.599299 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578] mod_wsgi (pid=12): Exception occurred processing WSGI script '/srv/www/app/apache/apache.wsgi'.
[Fri Jan 13 14:38:04.599340 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578] Traceback (most recent call last):
[Fri Jan 13 14:38:04.599385 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578]   File "/srv/www/app/apache/apache.wsgi", line 10, in <module>
[Fri Jan 13 14:38:04.599438 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578]     from main import app as application
[Fri Jan 13 14:38:04.599469 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578]   File "/srv/www/app/main.py", line 15, in <module>
[Fri Jan 13 14:38:04.599508 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578]     imgData = os.listdir(ROOT_DIR + "/static/data/imgData")
[Fri Jan 13 14:38:04.599549 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578] OSError: [Errno 2] No such file or directory: '/srv/www/app/static/data/imgData'
[Fri Jan 13 14:38:11.103681 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736] mod_wsgi (pid=12): Target WSGI script '/srv/www/app/apache/apache.wsgi' cannot be loaded as Python module.
[Fri Jan 13 14:38:11.103759 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736] mod_wsgi (pid=12): Exception occurred processing WSGI script '/srv/www/app/apache/apache.wsgi'.
[Fri Jan 13 14:38:11.103814 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736] Traceback (most recent call last):
[Fri Jan 13 14:38:11.103854 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736]   File "/srv/www/app/apache/apache.wsgi", line 10, in <module>
[Fri Jan 13 14:38:11.103905 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736]     from main import app as application
[Fri Jan 13 14:38:11.103936 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736]   File "/srv/www/app/main.py", line 15, in <module>
[Fri Jan 13 14:38:11.103975 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736]     imgData = os.listdir(ROOT_DIR + "/static/data/imgData")
[Fri Jan 13 14:38:11.104018 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736] OSError: [Errno 2] No such file or directory: '/srv/www/app/static/data/imgData'
[Fri Jan 13 14:38:11.259044 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736] mod_wsgi (pid=12): Target WSGI script '/srv/www/app/apache/apache.wsgi' cannot be loaded as Python module.
[Fri Jan 13 14:38:11.259110 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736] mod_wsgi (pid=12): Exception occurred processing WSGI script '/srv/www/app/apache/apache.wsgi'.
[Fri Jan 13 14:38:11.259154 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736] Traceback (most recent call last):
[Fri Jan 13 14:38:11.259196 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736]   File "/srv/www/app/apache/apache.wsgi", line 10, in <module>
[Fri Jan 13 14:38:11.259251 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736]     from main import app as application
[Fri Jan 13 14:38:11.259282 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736]   File "/srv/www/app/main.py", line 15, in <module>
[Fri Jan 13 14:38:11.259322 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736]     imgData = os.listdir(ROOT_DIR + "/static/data/imgData")
[Fri Jan 13 14:38:11.259367 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736] OSError: [Errno 2] No such file or directory: '/srv/www/app/static/data/imgData'
[Fri Jan 13 14:38:17.111006 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578] mod_wsgi (pid=12): Target WSGI script '/srv/www/app/apache/apache.wsgi' cannot be loaded as Python module.
[Fri Jan 13 14:38:17.111105 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578] mod_wsgi (pid=12): Exception occurred processing WSGI script '/srv/www/app/apache/apache.wsgi'.
[Fri Jan 13 14:38:17.111166 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578] Traceback (most recent call last):
[Fri Jan 13 14:38:17.111222 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578]   File "/srv/www/app/apache/apache.wsgi", line 10, in <module>
[Fri Jan 13 14:38:17.111295 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578]     from main import app as application
[Fri Jan 13 14:38:17.111326 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578]   File "/srv/www/app/main.py", line 15, in <module>
[Fri Jan 13 14:38:17.111366 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578]     imgData = os.listdir(ROOT_DIR + "/static/data/imgData")
[Fri Jan 13 14:38:17.111425 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578] OSError: [Errno 2] No such file or directory: '/srv/www/app/static/data/imgData'
[Fri Jan 13 14:38:17.329637 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578] mod_wsgi (pid=12): Target WSGI script '/srv/www/app/apache/apache.wsgi' cannot be loaded as Python module.
[Fri Jan 13 14:38:17.329705 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578] mod_wsgi (pid=12): Exception occurred processing WSGI script '/srv/www/app/apache/apache.wsgi'.
[Fri Jan 13 14:38:17.329747 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578] Traceback (most recent call last):
[Fri Jan 13 14:38:17.329788 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578]   File "/srv/www/app/apache/apache.wsgi", line 10, in <module>
[Fri Jan 13 14:38:17.329842 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578]     from main import app as application
[Fri Jan 13 14:38:17.329874 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578]   File "/srv/www/app/main.py", line 15, in <module>
[Fri Jan 13 14:38:17.329914 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578]     imgData = os.listdir(ROOT_DIR + "/static/data/imgData")
[Fri Jan 13 14:38:17.329958 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:58578] OSError: [Errno 2] No such file or directory: '/srv/www/app/static/data/imgData'
[Fri Jan 13 14:38:24.264851 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736] mod_wsgi (pid=12): Target WSGI script '/srv/www/app/apache/apache.wsgi' cannot be loaded as Python module.
[Fri Jan 13 14:38:24.264926 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736] mod_wsgi (pid=12): Exception occurred processing WSGI script '/srv/www/app/apache/apache.wsgi'.
[Fri Jan 13 14:38:24.264966 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736] Traceback (most recent call last):
[Fri Jan 13 14:38:24.265005 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736]   File "/srv/www/app/apache/apache.wsgi", line 10, in <module>
[Fri Jan 13 14:38:24.265057 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736]     from main import app as application
[Fri Jan 13 14:38:24.265087 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736]   File "/srv/www/app/main.py", line 15, in <module>
[Fri Jan 13 14:38:24.265126 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736]     imgData = os.listdir(ROOT_DIR + "/static/data/imgData")
[Fri Jan 13 14:38:24.265169 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:32736] OSError: [Errno 2] No such file or directory: '/srv/www/app/static/data/imgData'
[Fri Jan 13 14:38:34.412607 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736] mod_wsgi (pid=12): Target WSGI script '/srv/www/app/apache/apache.wsgi' cannot be loaded as Python module.
[Fri Jan 13 14:38:34.412698 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736] mod_wsgi (pid=12): Exception occurred processing WSGI script '/srv/www/app/apache/apache.wsgi'.
[Fri Jan 13 14:38:34.412749 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736] Traceback (most recent call last):
[Fri Jan 13 14:38:34.412792 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736]   File "/srv/www/app/apache/apache.wsgi", line 10, in <module>
[Fri Jan 13 14:38:34.412854 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736]     from main import app as application
[Fri Jan 13 14:38:34.412888 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736]   File "/srv/www/app/main.py", line 15, in <module>
[Fri Jan 13 14:38:34.412930 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736]     imgData = os.listdir(ROOT_DIR + "/static/data/imgData")
[Fri Jan 13 14:38:34.412974 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736] OSError: [Errno 2] No such file or directory: '/srv/www/app/static/data/imgData'
[Fri Jan 13 14:38:42.151137 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578] mod_wsgi (pid=12): Target WSGI script '/srv/www/app/apache/apache.wsgi' cannot be loaded as Python module.
[Fri Jan 13 14:38:42.151215 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578] mod_wsgi (pid=12): Exception occurred processing WSGI script '/srv/www/app/apache/apache.wsgi'.
[Fri Jan 13 14:38:42.151256 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578] Traceback (most recent call last):
[Fri Jan 13 14:38:42.151295 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578]   File "/srv/www/app/apache/apache.wsgi", line 10, in <module>
[Fri Jan 13 14:38:42.151347 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578]     from main import app as application
[Fri Jan 13 14:38:42.151378 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578]   File "/srv/www/app/main.py", line 15, in <module>
[Fri Jan 13 14:38:42.151418 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578]     imgData = os.listdir(ROOT_DIR + "/static/data/imgData")
[Fri Jan 13 14:38:42.151480 2017] [wsgi:error] [pid 12:tid 140470460430080] [remote 128.211.233.228:58578] OSError: [Errno 2] No such file or directory: '/srv/www/app/static/data/imgData'
[Fri Jan 13 14:38:42.744349 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736] mod_wsgi (pid=12): Target WSGI script '/srv/www/app/apache/apache.wsgi' cannot be loaded as Python module.
[Fri Jan 13 14:38:42.744473 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736] mod_wsgi (pid=12): Exception occurred processing WSGI script '/srv/www/app/apache/apache.wsgi'.
[Fri Jan 13 14:38:42.744562 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736] Traceback (most recent call last):
[Fri Jan 13 14:38:42.744650 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736]   File "/srv/www/app/apache/apache.wsgi", line 10, in <module>
[Fri Jan 13 14:38:42.744762 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736]     from main import app as application
[Fri Jan 13 14:38:42.744832 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736]   File "/srv/www/app/main.py", line 15, in <module>
[Fri Jan 13 14:38:42.744921 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736]     imgData = os.listdir(ROOT_DIR + "/static/data/imgData")
[Fri Jan 13 14:38:42.745013 2017] [wsgi:error] [pid 12:tid 140470452029184] [remote 128.211.233.228:32736] OSError: [Errno 2] No such file or directory: '/srv/www/app/static/data/imgData'
